#ifndef ATM_DEF_H
#define ATM_DEF_H

#define MAX_DEPOSIT		10000
#define MIN_DEPOSIT		10
#define MAX_WITHDRAW	1000
#define MIN_WITHDRAW	MIN_DEPOSIT

typedef enum {
	ATM_SUCCESS = 0,
	ATM_FAILURE,
	ATM_WRONG_PIN,
	ATM_INVALID_AMOUNT,
	ATM_INSUFF_FUNDS,
}atm_status_t;

enum {
	ATM_WITHDRAW = 0,
	ATM_DEPOSIT,
	ATM_INQUIRY,
	ATM_RETURN_CARD
};

typedef enum {
	ATM_STATE_IDLE = 0,
	ATM_STATE_CARD_INSERTED,
	ATM_STATE_PIN_CHECK,
	ATM_STATE_OPERATIONS,
	ATM_STATE_ACCOUNT_LOCK,
	ATM_STATE_RETURN_CARD
}atm_state_t;

#endif /* ATM_DEF_H */