#ifndef ATM_DEF_H
#define ATM_DEF_H

#define MAX_DEPOSITS		10000
#define MIN_DEPOSITS		10

#define MIN_WITHDRAW		MIN_DEPOSITS
#define MAX_WITHDRAW		1000

//#define FLAG_UPDATE_PINS	0b00001111
//#define FLAG_UPDATE_BALA	0b11110000

/* This is USB Serial Number */
#define ACCOUNT_NUM		20

#define PIN_SIZE		4

typedef enum {
	ATM_SUCCESS = 0,
	ATM_FAILURE,
	ATM_WRONG_PIN,
	ATM_INVALID_AMOUNT,
	ATM_INSUFF_FUNDS,
	ATM_MEM_ERROR
}atm_status_t;

enum {
	ATM_WITHDRAW = 0,
	ATM_DEPOSIT,
	ATM_INQUIRY,
	ATM_CHANGE_PIN,
	ATM_RETURN_CARD
};

typedef enum {
	ATM_STATE_IDLE = 0,
	ATM_STATE_CARD_INSERTED,
	ATM_STATE_PIN_CHECK,
	ATM_STATE_OPERATIONS,
	ATM_STATE_ACCOUNT_LOCK,
	ATM_STATE_RETURN_CARD
}atm_state_t;

#endif /* ATM_DEF_H */